config/routes.rb
Rails.application.routes.draw do
  
##### IN USE ##############
###### USER ###############
  root 'welcome#index'

  post 'create_users' => 'welcome#users'

  get 'users' => 'welcome#users'

  get 'show_user'=>'welcome#show_user'

  get 'edit_user'=>'welcome#edit_user'

  post 'update_user'=>'welcome#update_user'

#### PRODUCTS ################
	post 'products'=>'welcome#create_products'

	get 'products'=>'welcome#products'

	get 'show_product'=> 'welcome#show_product'

	get 'edit_product'=>'welcome#edit_product'

	patch 'product'=>'welcome#update_product'


### UN EDITTED ###################
 	get 'welcome/index'

  get 'welcome/users'

  get 'welcome/products'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
# ## USERS ######################
  def users
  	if params[:name] !=nil && params[:age] != nil
  		user = User.create(name: params[:name], age: params[:age])
  	end
  		@users = User.all
	end

	def show_user
		@user = User.find(params[:id])
	end

	def edit_user
		@user = User.find(params[:id])

	end

	def update_user
		user = User.find(params[:id])
		user.update(name: params[:name],age: params[:age])
		redirect_to show_user_path(id: user.id)
	end

##### PRODUCTS #########################

	def index
		@product = Product.new
	end

	def create_products
		product = Product.create(product_params)
		redirect_to products_path
	end

  def products
  		@products = Product.all
  end

  def show_product
  	@product = Product.find(params[:id])
  end

  def edit_product
  	@product = Product.find(params[:id])
  end

  def update_product
  	@product = Product.find(params["product"][:id])
  	@product.update(product_params)
  	redirect_to show_product_path(id: @product.id)
  end

  private

  	def product_params
  		params.require(:product).permit(:name, :price, :quantity)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScaffoldFree</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/edit_product.html.erb
<div style="margin:50px;">
	<h1>Product Input</h1>
	<h3>Create a Product</h3>
	<%= form_for(@product, url:product_path, method: :patch) do |f| %>
			<%= f.text_field :name, value: @product.name %><br />
			<%= f.number_field :price, value: @product.price %><br />
			<%= f.number_field :quantity, value: @product.quantity %><br />
			<%= f.hidden_field :id, value: @product.id %>

			<%= f.submit %>
	<% end %>

	<p><%= link_to "All Products", products_path %></p>
</div>

app/views/welcome/edit_user.html.erb
<div style="margin:50px;">
	<h1><%= @user.name %></h1>
	<h3>Edit User</h3>
	<%= form_tag update_user_path do %>
			<%=text_field_tag :name, @user.name %><br />
			<%= number_field_tag :age, @user.age %><br />
			<%= hidden_field_tag :id, @user.id %><br />
			<%= submit_tag "Edit Profile" %>


	<% end %>

	<p><%= link_to "All Users", users_path %></p>



</div>

app/views/welcome/index.html.erb
<div style="margin:50px;">
	<h1>Home Page</h1>
	<h3>Create a User</h3>
	<%= form_tag create_users_path do %>
			<%=text_field_tag :name, nil, placeholder: "Your Name" %><br />
			<%= number_field_tag :age, nil, placeholder: "Your Age" %><br />
			<%= submit_tag "Create Profile" %>


	<% end %>

	<p><%= link_to "All Users", users_path %></p>
</div>


<div style="margin:50px;">
	<h1>Product Input</h1>
	<h3>Create a Product</h3>
	<%= form_for @product do |f| %>
			<%= f.text_field :name, placeholder: "Product Name" %><br />
			<%= f.number_field :price, placeholder: "Price", step: :any %><br />
			<%= f.number_field :quantity, placeholder: "Quantity" %><br />
			<%= f.submit %>
	<% end %>

	<p><%= link_to "All Products", products_path %></p>
</div>

app/views/welcome/products.html.erb
<div style="margin:50px";>

	<h1> All Products</h1>

	<table >
		<tr>
			<th>Name</th>
			<th>Price</th>
			<th>Quantity</th>
		</tr>

		<% @products.each do |p| %>
				<tr>
					<td><%= link_to p.name, show_product_path(id: p.id) %></td>
					<td><%= number_to_currency(p.price) %></td>
					<td><%= p.quantity %></td>
				</tr>
		<% end %>
	</table>

	<p>
		<%= link_to "Return to Index", root_path %>
	</p>
</div>

app/views/welcome/show_product.html.erb
<div style="margin:50px;">

	<h1> Info About <%= @product.name %> Product</h1>
	<p><strong>Name: </strong><%= @product.name %></p>
	<p><strong>Price: </strong><%= number_to_currency(@product.price) %></p>
	<p><strong>Quantity: </strong><%= @product.quantity %></p>

	<p><%= link_to "Edit Product", edit_product_path(id: params[:id] )%></p>

	<p><%= link_to "All Products", products_path %></p>

</div>

app/views/welcome/show_user.html.erb
<div style="margin:50px;">

<h1>Info About <%= @user.name %></h1>
	<p><strong>Name: </strong><%= @user.name %></p>
	<p><strong>Age: </strong><%= @user.age %></p>

	<p><%= link_to "Edit User", edit_user_path(id: @user.id) %>	</p>

	<p><%= link_to "All Users", users_path %></p>
	<p><%= link_to "Back to Index", root_path %></p>
</div>

app/views/welcome/users.html.erb
<div style="margin:50px";>

	<h1> All Users</h1>

	<table >
		<tr>
			<th>Name</th>
			<th>Age</th>
		</tr>

		<% @users.each do |user| %>
				<tr>
					<td><%= link_to user.name, show_user_path(id: user.id) %></td>
					<td><%= user.age %></td>
				</tr>
		<% end %>
	</table>

	<p>
		<%= link_to "Return to Index", root_path %>
	</p>
</div>